version: '3' 

services:

  redis:
    image: redis:latest
    restart: on-failure
    expose:
      - "6379"

  db:
    image: postgres:13
    restart: on-failure
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PG_DATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env.
    depends_on:
      db:
        condition: service_healthy

  celery:
    build: .
    env_file:
      - .env
    command: celery -A config worker -l INFO
    restart: on-failure
    depends_on:
        - redis
        - app
        - db

  celery-beat:
    build: .
    env_file:
      - .env
    command: celery -A config beat -l INFO
    restart: on-failure
    depends_on:
        - redis
        - app
        - db